In [1]:
!pip install torch torchvision

Defaulting to user installation because normal site-packages is not writeable
     -------------------------------------- 162.5/162.5 MB 1.4 MB/s eta 0:00:00
     ---------------------------------------- 1.1/1.1 MB 2.2 MB/s eta 0:00:00


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [4]:
import torch
import numpy as np

In [36]:
# Создайте случайный FloatTensor размера 3x4x5

a = torch.randn(3, 4, 5)
a

tensor([[[ 0.3347, -1.6483,  1.2097,  0.9934, -1.8260],
         [ 0.2596, -0.1475, -0.6244,  0.5392, -1.0114],
         [-4.1803,  1.9568, -1.4022, -0.9676,  0.9447],
         [-0.5394,  1.2781, -0.8961, -0.2812,  1.3011]],

        [[ 2.0366,  0.2471,  0.2099, -0.4184, -2.0488],
         [ 1.3048,  1.1757,  0.7457, -0.0757, -0.0091],
         [ 1.2108,  0.2931,  1.1555, -0.2952,  0.3551],
         [-0.5234, -1.0387,  0.1718,  1.9828, -0.2022]],

        [[-1.3320, -1.8451, -0.1728, -0.5100,  0.3051],
         [-0.7681,  0.4207, -0.6163,  0.3507,  0.0641],
         [-1.7899,  0.2129,  0.8127,  1.3950,  1.5065],
         [ 1.1043,  1.5445,  0.3526,  1.6422, -0.8301]]])

In [27]:
# Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [28]:
# Приведите его к форме 6 X 10
a = a.reshape(6, 10)
a.shape

torch.Size([6, 10])

In [29]:
# Создайте случайный IntTensor размера 10
b = torch.randint(10, size=(10,)).int()
b.type()

'torch.IntTensor'

In [30]:
# Умножьте созданный FloatTensor на созданный IntTensor поэлементно
a * b

tensor([[-0.0000e+00,  1.0303e+00, -4.3241e+00, -1.1330e+00,  2.2275e+00,
          6.6268e+00,  8.0440e+00, -4.2265e+00,  3.2592e+00, -0.0000e+00],
        [-0.0000e+00,  5.7723e-01, -1.2588e+00, -9.1342e-03, -1.7073e+00,
         -8.9304e+00, -1.1684e+01,  5.2668e+00, -5.7864e-01,  0.0000e+00],
        [ 0.0000e+00, -2.1079e-01,  1.3680e+01, -1.6987e-01,  7.0608e-01,
          6.5731e+00,  2.6494e+00, -1.0848e+01, -3.6561e+00,  0.0000e+00],
        [ 0.0000e+00, -1.1255e+00,  1.0483e+01,  8.0099e+00, -1.4278e+00,
         -6.6846e+00, -1.1892e+01, -5.1316e+00, -2.4702e+00,  0.0000e+00],
        [-0.0000e+00,  9.1101e-01, -5.0653e+00, -6.8982e+00,  7.4176e-03,
         -3.4256e+00, -9.2118e+00, -6.9743e+00, -1.4643e+00, -0.0000e+00],
        [-0.0000e+00, -7.0815e-01,  1.2223e+01, -4.4416e+00, -8.6444e-01,
          9.2425e+00,  6.9009e+00,  6.8661e+00,  9.5557e+00,  0.0000e+00]])

In [33]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6 Подсказка: .dot может не подойти
torch.matmul(a, a.T)

tensor([[ 8.3933, -4.8002, -0.1877, -7.5959,  0.8348,  2.5660],
        [-4.8002,  7.6482, -5.6065,  3.6410,  2.9681, -3.9771],
        [-0.1877, -5.6065, 12.4808,  3.9352, -2.1201,  2.3938],
        [-7.5959,  3.6410,  3.9352, 12.5631, -1.4877, -2.9741],
        [ 0.8348,  2.9681, -2.1201, -1.4877,  6.6832, -4.9231],
        [ 2.5660, -3.9771,  2.3938, -2.9741, -4.9231, 17.3264]])

In [34]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor([1]).float()
x.requires_grad = True
z = torch.tensor([.5]).float()
z.requires_grad = True
t = torch.tensor([2]).float()
t.requires_grad = True
y = x**3 + z - 75*t
y.backward()
print(x.grad, z.grad, t.grad)

tensor([3.]) tensor([1.]) tensor([-75.])


In [35]:
# Создайте единичный тензор размера 5x6
c = torch.ones((5, 6))
c

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [37]:
# Переведите его в формат numpy
d = c.numpy()
d

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)